# Generated by Django 5.0 on 2025-12-02 06:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_especial', models.BooleanField(default=False, help_text='True para: festivo, incapacidad, ausencia no justificada, dominical')),
                ('solo_con_contrato', models.BooleanField(default=False, help_text='True para festivos y dominicales')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Quincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_cierre_registro', models.DateField(help_text='15 días después de fecha_fin para permitir correcciones')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_CALCULO', 'En Cálculo'), ('CALCULADA', 'Calculada'), ('PAGADA', 'Pagada')], default='ABIERTA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quincena',
                'verbose_name_plural': 'Quincenas',
                'ordering': ['-año', '-mes', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad según unidad de medida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Labor',
                'verbose_name_plural': 'Registros de Labores',
                'ordering': ['-fecha', 'trabajador'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('DIGITADOR', 'Digitador'), ('SOLO_LECTURA', 'Solo Lectura')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.JSONField(default=dict, help_text='Permisos específicos del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CON_CONTRATO', 'Con Contrato'), ('SIN_CONTRATO', 'Sin Contrato')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('aplica_deducciones', models.BooleanField(default=False, help_text='True para trabajadores con contrato')),
                ('aplica_dominicales', models.BooleanField(default=False, help_text='True para trabajadores con contrato')),
                ('aplica_auxilio_transporte', models.BooleanField(default=False, help_text='True para trabajadores con contrato')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PEP', 'Permiso Especial de Permanencia')], max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('lugar_expedicion_documento', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('eps', models.CharField(blank=True, max_length=100, verbose_name='EPS')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20)),
                ('numero_cuenta_bancaria', models.CharField(blank=True, help_text='Debe estar encriptado en producción', max_length=50)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('DIA', 'Día'), ('UNIDAD', 'Unidad'), ('HECTAREA', 'Hectárea'), ('METRO', 'Metro')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='VariablesNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SALARIO_MINIMO', 'Salario Mínimo'), ('AUXILIO_TRANSPORTE', 'Auxilio de Transporte'), ('PORCENTAJE_SALUD', 'Porcentaje Salud'), ('PORCENTAJE_PENSION', 'Porcentaje Pensión')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variable de Nómina',
                'verbose_name_plural': 'Variables de Nómina',
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('es_activo', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW_SENSITIVE', 'Ver Información Sensible')], max_length=20)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_creados', to=settings.AUTH_USER_MODEL)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.labor')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_devengado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-quincena', 'trabajador'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEVENGO', 'Devengo'), ('DEDUCCION', 'Deducción')], max_length=20)),
                ('concepto', models.CharField(choices=[('LABOR', 'Labor'), ('DOMINICAL', 'Dominical'), ('FESTIVO', 'Festivo'), ('AUXILIO_TRANSPORTE', 'Auxilio de Transporte'), ('SALUD', 'Salud'), ('PENSION', 'Pensión'), ('PRESTAMO', 'Préstamo'), ('AJUSTE_MANUAL', 'Ajuste Manual')], max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.labor')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.nomina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'ordering': ['nomina', 'tipo', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_prestamo', models.DateField()),
                ('tipo_pago', models.CharField(choices=[('UNICO', 'Pago Único'), ('CUOTAS', 'Cuotas')], max_length=20)),
                ('numero_cuotas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_descuento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESCONTADA', 'Descontada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_descontadas', to='core.nomina')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamo')),
            ],
            options={
                'verbose_name': 'Cuota de Préstamo',
                'verbose_name_plural': 'Cuotas de Préstamos',
                'ordering': ['prestamo', 'numero_cuota'],
            },
        ),
        migrations.AddConstraint(
            model_name='quincena',
            constraint=models.UniqueConstraint(fields=('año', 'mes', 'numero'), name='unique_quincena'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='quincena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='core.quincena'),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='quincena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_descontadas', to='core.quincena'),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='labor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='core.labor'),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='quincena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.quincena'),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='core.tipocontrato'),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_labor', to='core.trabajador'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='core.trabajador'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='core.trabajador'),
        ),
        migrations.AddField(
            model_name='labor',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labores', to='core.unidadmedida'),
        ),
        migrations.AddField(
            model_name='variablesnomina',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['tabla_afectada', 'registro_id'], name='core_audito_tabla_a_006222_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-created_at'], name='core_audito_created_403745_idx'),
        ),
        migrations.AddConstraint(
            model_name='listaprecios',
            constraint=models.UniqueConstraint(fields=('labor', 'fecha_inicio_vigencia'), name='unique_labor_fecha_inicio'),
        ),
        migrations.AddIndex(
            model_name='registrolabor',
            index=models.Index(fields=['trabajador', 'quincena', 'fecha'], name='core_regist_trabaja_023edf_idx'),
        ),
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(fields=('trabajador', 'quincena'), name='unique_nomina_trabajador_quincena'),
        ),
    ]
