# Generated by Django 5.0 on 2025-12-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_finca_trabajador_arl_trabajador_tipo_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrolabor',
            options={'ordering': ['-fecha', 'trabajador'], 'verbose_name': 'Registro de Labor', 'verbose_name_plural': 'Registros de Labor'},
        ),
        migrations.RemoveIndex(
            model_name='registrolabor',
            name='core_regist_trabaja_023edf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='registrolabor',
            unique_together={('trabajador', 'fecha', 'quincena')},
        ),
        migrations.AlterModelTable(
            name='registrolabor',
            table='registros_labor',
        ),
    ]
