# Generated by Django 5.0 on 2025-12-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registrolabor_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrolabor',
            unique_together=set(),
        ),
    ]
