# Generated by Django 5.0 on 2025-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registrolabor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='es_administrativo',
            field=models.BooleanField(default=False, help_text='Si es True, se le paga salario fijo en lugar de por labores', verbose_name='Es Administrativo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='salario_quincenal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario fijo quincenal (solo para administrativos)', max_digits=10, null=True, verbose_name='Salario Quincenal'),
        ),
    ]
