# Generated by Django 5.0 on 2025-12-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trabajador_es_administrativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='deducciones_adicionales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sanciones, descuentos varios, etc.', max_digits=10, verbose_name='Deducciones Adicionales'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='descripcion_deducciones_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de Deducciones Adicionales'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='descripcion_devengos_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de Devengos Adicionales'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='devengos_adicionales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonos, horas extra, etc.', max_digits=10, verbose_name='Devengos Adicionales'),
        ),
    ]
