# Generated by Django 5.0 on 2025-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nomina_deducciones_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
