# Generated by Django 5.0 on 2026-01-16 02:17

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_role_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa (ej: AGROMAXD S.A.S.)', max_length=200, verbose_name='Razón Social')),
                ('nit', models.CharField(help_text='Número de Identificación Tributaria (ej: 901944190-0)', max_length=20, verbose_name='NIT')),
                ('representante_legal', models.CharField(help_text='Nombre completo del representante legal', max_length=200, verbose_name='Representante Legal')),
                ('tipo_documento_representante', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=10, verbose_name='Tipo Documento Representante')),
                ('documento_representante', models.CharField(help_text='Número de documento del representante legal', max_length=20, verbose_name='Documento Representante')),
                ('correo', models.EmailField(help_text='Correo oficial de la empresa', max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Teléfono de contacto de la empresa', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(help_text='Dirección principal de la empresa', max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde opera la empresa', max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('logo_path', models.CharField(default='logos/logo_completo.jpeg', help_text='Ruta al archivo del logo (relativa a static/)', max_length=300, verbose_name='Ruta del Logo')),
                ('periodo_pago', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal')], default='QUINCENAL', max_length=20, verbose_name='Período de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nacionalidad',
            field=models.CharField(default='COLOMBIANA', help_text='Nacionalidad del trabajador', max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('CONSULTA', 'Consulta')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(editable=False, help_text='Generado automáticamente: CTR-YYYY-NNNN', max_length=20, unique=True, verbose_name='Número de Contrato')),
                ('tipo_contrato', models.CharField(choices=[('TERMINO_FIJO', 'Término Fijo'), ('TERMINO_INDEFINIDO', 'Término Indefinido')], default='TERMINO_FIJO', max_length=20, verbose_name='Tipo de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Requerido para contratos de término fijo', null=True, verbose_name='Fecha de Finalización')),
                ('cargo', models.CharField(help_text='Cargo desempeñado según contrato', max_length=100, verbose_name='Cargo')),
                ('salario_pactado', models.DecimalField(decimal_places=2, help_text='Salario acordado en el contrato (mensual)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salario Pactado')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_liquidacion', models.DateField(blank=True, help_text='Fecha en que se pagaron las prestaciones', null=True, verbose_name='Fecha de Liquidación')),
                ('motivo_finalizacion', models.CharField(blank=True, choices=[('VENCIMIENTO_TERMINO', 'Vencimiento del Término'), ('RENUNCIA_TRABAJADOR', 'Renuncia del Trabajador'), ('DESPIDO_JUSTA_CAUSA', 'Despido con Justa Causa'), ('DESPIDO_SIN_JUSTA_CAUSA', 'Despido sin Justa Causa'), ('MUTUO_ACUERDO', 'Mutuo Acuerdo'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Motivo de Finalización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CONTRATO', 'Contrato Original'), ('ANEXO', 'Anexo'), ('OTRO_SI', 'Otro Sí'), ('TERMINACION', 'Acta de Terminación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del documento', max_length=200, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(help_text='Documento en PDF', upload_to='contratos/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_documento', models.DateField(default=datetime.date.today, verbose_name='Fecha del Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.contrato', verbose_name='Contrato')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_contratos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contratos',
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['trabajador', 'estado'], name='core_contra_trabaja_ec8702_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado', 'fecha_fin'], name='core_contra_estado_f66c8c_idx'),
        ),
    ]
