# Generated by Django 5.0 on 2026-01-26 01:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ensure_nacionalidad_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotaprestamo',
            options={'ordering': ['prestamo', 'numero_cuota'], 'verbose_name': 'Cuota de Adelanto', 'verbose_name_plural': 'Cuotas de Adelantos'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_prestamo'], 'verbose_name': 'Adelanto de Nómina', 'verbose_name_plural': 'Adelantos de Nómina'},
        ),
        migrations.CreateModel(
            name='PILA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('total_ibc', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total IBC de todos los trabajadores', max_digits=15)),
                ('total_salud', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total aporte salud empleador (8.5%)', max_digits=15)),
                ('total_pension', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total aporte pensión empleador (12%)', max_digits=15)),
                ('total_arl', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total aporte ARL (0.522%)', max_digits=15)),
                ('total_caja', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total aporte Caja Compensación (4%)', max_digits=15)),
                ('total_aportes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total aportes seguridad social', max_digits=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('numero_planilla', models.CharField(blank=True, help_text='Número de planilla PILA', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PILA',
                'verbose_name_plural': 'PILAs',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='DetallePILA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibc', models.DecimalField(decimal_places=2, help_text='Ingreso Base de Cotización del mes', max_digits=12)),
                ('dias_cotizados', models.IntegerField(default=30, help_text='Días cotizados en el mes')),
                ('aporte_salud', models.DecimalField(decimal_places=2, help_text='Aporte salud empleador 8.5%', max_digits=12)),
                ('aporte_pension', models.DecimalField(decimal_places=2, help_text='Aporte pensión empleador 12%', max_digits=12)),
                ('aporte_arl', models.DecimalField(decimal_places=2, help_text='Aporte ARL 0.522%', max_digits=12)),
                ('aporte_caja', models.DecimalField(decimal_places=2, help_text='Aporte Caja Compensación 4%', max_digits=12)),
                ('total_aportes', models.DecimalField(decimal_places=2, help_text='Total aportes del trabajador', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportes_pila', to='core.nomina')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_pila', to='core.trabajador')),
                ('pila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pila')),
            ],
            options={
                'verbose_name': 'Detalle PILA',
                'verbose_name_plural': 'Detalles PILA',
                'ordering': ['pila', 'trabajador__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionPrestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario devengado del mes', max_digits=12)),
                ('cesantias', models.DecimalField(decimal_places=2, help_text='Provisión cesantías 8.33%', max_digits=12)),
                ('intereses_cesantias', models.DecimalField(decimal_places=2, help_text='Provisión intereses cesantías 1%', max_digits=12)),
                ('prima', models.DecimalField(decimal_places=2, help_text='Provisión prima 8.33%', max_digits=12)),
                ('vacaciones', models.DecimalField(decimal_places=2, help_text='Provisión vacaciones 4.17%', max_digits=12)),
                ('total_provision', models.DecimalField(decimal_places=2, help_text='Total provisión del mes', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisiones', to='core.nomina')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisiones_prestaciones', to='core.trabajador')),
            ],
            options={
                'verbose_name': 'Provisión Prestaciones',
                'verbose_name_plural': 'Provisiones Prestaciones',
                'ordering': ['-año', '-mes', 'trabajador__apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ResumenPrestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('total_salario_base', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total salarios devengados', max_digits=15)),
                ('total_cesantias', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_intereses_cesantias', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_prima', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_vacaciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_provisiones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('num_trabajadores', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_prestaciones_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen Prestaciones',
                'verbose_name_plural': 'Resúmenes Prestaciones',
                'ordering': ['-año', '-mes'],
            },
        ),
        migrations.AddConstraint(
            model_name='pila',
            constraint=models.UniqueConstraint(fields=('mes', 'año'), name='unique_pila_periodo'),
        ),
        migrations.AddConstraint(
            model_name='detallepila',
            constraint=models.UniqueConstraint(fields=('pila', 'trabajador'), name='unique_pila_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='provisionprestaciones',
            constraint=models.UniqueConstraint(fields=('mes', 'año', 'trabajador'), name='unique_provision_periodo_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='resumenprestaciones',
            constraint=models.UniqueConstraint(fields=('mes', 'año'), name='unique_resumen_prestaciones_periodo'),
        ),
    ]
