# Generated by Django 5.0 on 2026-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_obligaciones_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fincas_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Fincas que este usuario puede ver. Admins ven todas.', related_name='usuarios_asignados', to='core.finca'),
        ),
    ]
