# Generated by Django 5.1.4 on 2026-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pila_tipo_quincena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(choices=[('DIA', 'Día'), ('UNIDAD', 'Unidad'), ('HECTAREA', 'Hectárea'), ('METRO', 'Metro'), ('HORAS', 'Horas')], max_length=20, unique=True),
        ),
    ]
