# Generated by Django 5.1.4 on 2026-04-19 23:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agregar_horas_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenomina',
            name='concepto',
            field=models.CharField(choices=[('LABOR', 'Labor'), ('DOMINICAL', 'Dominical'), ('FESTIVO', 'Festivo'), ('AUXILIO_TRANSPORTE', 'Auxilio de Transporte'), ('SALUD', 'Salud'), ('PENSION', 'Pensión'), ('PRESTAMO', 'Préstamo'), ('AJUSTE_MANUAL', 'Ajuste Manual'), ('DEVENGO_ADICIONAL', 'Devengo Adicional'), ('DEDUCCION_ADICIONAL', 'Deducción Adicional')], max_length=50),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('AGROQUIMICOS', 'Agroquímicos'), ('MATERIALES', 'Materiales'), ('HERRAMIENTAS', 'Herramientas'), ('COMBUSTIBLES', 'Combustibles'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('unidad', models.CharField(choices=[('KG', 'Kilogramos'), ('LITROS', 'Litros'), ('UNIDADES', 'Unidades'), ('ROLLOS', 'Rollos'), ('METROS', 'Metros'), ('SACOS', 'Sacos'), ('CAJAS', 'Cajas')], default='UNIDADES', max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.finca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_despues', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=30)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
