# Generated by Django 5.1.4 on 2026-06-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_inventario_stock_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='stockfinca',
            options={'ordering': ['producto__categoria', 'producto__nombre', 'bodega__nombre'], 'verbose_name': 'Stock por Bodega', 'verbose_name_plural': 'Stocks por Bodega'},
        ),
        migrations.RemoveField(
            model_name='stockfinca',
            name='finca',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_consumo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='core.lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='core.trabajador'),
        ),
        migrations.AddField(
            model_name='finca',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fincas', to='core.bodega'),
        ),
        migrations.AddField(
            model_name='stockfinca',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.bodega'),
        ),
    ]
