# Generated by Django 5.1.4 on 2026-06-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bodega_y_cambios_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolabor',
            name='color_cinta',
            field=models.CharField(blank=True, choices=[('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('AMARILLO', 'Amarillo'), ('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSADO', 'Rosado'), ('CAFE', 'Café')], help_text='Solo para labor Control', max_length=10),
        ),
        migrations.AddField(
            model_name='registrolabor',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_labor', to='core.lote'),
        ),
        migrations.CreateModel(
            name='LaborInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, help_text='Unidades de labor por 1 unidad del producto de bodega', max_digits=10)),
                ('es_aproximado', models.BooleanField(default=False, help_text='True cuando la conversión es estimada (ej. abono)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insumo', to='core.labor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_insumos', to='core.producto')),
            ],
            options={
                'verbose_name': 'Labor → Insumo',
                'verbose_name_plural': 'Labores → Insumos',
            },
        ),
    ]
