# Generated by Django 5.1.4 on 2026-06-13 22:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_labor_insumo_y_campos_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_embarque', models.DateField()),
                ('semana_año', models.CharField(help_text='Semana ISO del color principal cortado, formato YYYY-WW', max_length=8)),
                ('color_cinta', models.CharField(choices=[('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('AMARILLO', 'Amarillo'), ('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSADO', 'Rosado'), ('CAFE', 'Café')], help_text='Color de la semana principal cortada', max_length=10)),
                ('cintas_semana_actual', models.PositiveIntegerField(default=0)),
                ('cintas_semana_anterior', models.PositiveIntegerField(default=0)),
                ('cintas_semana_siguiente', models.PositiveIntegerField(default=0)),
                ('cajas_empacadas', models.PositiveIntegerField()),
                ('cajas_rechazadas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_creados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='core.lote')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'db_table': 'embarques',
                'ordering': ['-fecha_embarque'],
            },
        ),
        migrations.CreateModel(
            name='MataCaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cinta', models.CharField(choices=[('ROJO', 'Rojo'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('AMARILLO', 'Amarillo'), ('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSADO', 'Rosado'), ('CAFE', 'Café')], max_length=10)),
                ('semana_año', models.CharField(help_text='Semana de encintado, formato YYYY-WW (ej: 2026-23)', max_length=8)),
                ('cantidad_caidas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_reporte', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matas_caidas_creadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matas_caidas', to='core.lote')),
            ],
            options={
                'verbose_name': 'Mata Caída',
                'verbose_name_plural': 'Matas Caídas',
                'db_table': 'matas_caidas',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
