# Generated by Django 5.1.4 on 2026-06-14 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_produccion_matacaida_embarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='umbral_desviacion_produccion',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Porcentaje de desviación permitido antes de emitir alerta (default 10%)', max_digits=5, verbose_name='Umbral desviación producción (%)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='umbral_matas_sin_reportar',
            field=models.PositiveIntegerField(default=5, help_text='Número máximo de matas sin reportar antes de emitir alerta (default 5)', verbose_name='Umbral matas sin reportar'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matacaida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='direccion',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='documento_representante',
            field=models.CharField(max_length=20, verbose_name='Documento Representante'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='logo_path',
            field=models.CharField(default='logos/logo_completo.jpeg', max_length=300, verbose_name='Ruta del Logo'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='representante_legal',
            field=models.CharField(max_length=200, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cajas_empacadas',
            field=models.PositiveIntegerField(verbose_name='Cajas empacadas'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cajas_rechazadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Cajas rechazadas'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cintas_semana_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Cintas sem. actual'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cintas_semana_anterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Cintas sem. anterior'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='cintas_semana_siguiente',
            field=models.PositiveIntegerField(default=0, verbose_name='Cintas sem. siguiente'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='color_cinta',
            field=models.CharField(choices=[('MORADO', 'Morado'), ('CAFE', 'Café'), ('NEGRO', 'Negro'), ('NARANJA', 'Naranja'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('BLANCO', 'Blanco'), ('AZUL', 'Azul'), ('HABANO', 'Habano'), ('GRIS', 'Gris')], max_length=10, verbose_name='Color de cinta cortada'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='fecha_embarque',
            field=models.DateField(verbose_name='Fecha de embarque'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='core.finca', verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques', to='core.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='embarque',
            name='semana_año',
            field=models.CharField(help_text='Semana ISO del embarque (ej: 2026-24)', max_length=8, verbose_name='Semana (YYYY-WW)'),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='cantidad_caidas',
            field=models.PositiveIntegerField(verbose_name='Cantidad caídas'),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='color_cinta',
            field=models.CharField(choices=[('MORADO', 'Morado'), ('CAFE', 'Café'), ('NEGRO', 'Negro'), ('NARANJA', 'Naranja'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('BLANCO', 'Blanco'), ('AZUL', 'Azul'), ('HABANO', 'Habano'), ('GRIS', 'Gris')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matas_caidas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='fecha_reporte',
            field=models.DateField(verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matas_caidas', to='core.finca', verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matas_caidas', to='core.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='matacaida',
            name='semana_año',
            field=models.CharField(help_text='Semana ISO en la que se embolsó la mata (ej: 2026-23)', max_length=8, verbose_name='Semana (YYYY-WW)'),
        ),
        migrations.AlterModelTable(
            name='embarque',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matacaida',
            table=None,
        ),
    ]
