# Generated by Django 5.1.4 on 2026-06-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_liquidacion_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre de la plantilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción interna')),
                ('empleador_tipo', models.CharField(choices=[('EMPRESA', 'Empresa / Sociedad'), ('PERSONA_NATURAL', 'Persona Natural')], default='EMPRESA', max_length=20)),
                ('empleador_nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón Social del Empleador')),
                ('empleador_documento', models.CharField(max_length=20, verbose_name='NIT o Cédula del Empleador')),
                ('empleador_correo', models.EmailField(blank=True, max_length=254)),
                ('empleador_telefono', models.CharField(blank=True, max_length=20)),
                ('empleador_direccion', models.CharField(blank=True, max_length=200)),
                ('cargo_predeterminado', models.CharField(blank=True, max_length=100, verbose_name='Cargo por defecto')),
                ('objeto_contrato', models.TextField(help_text='Describe las labores específicas que realizará el trabajador.', verbose_name='Texto de la Primera Cláusula (objeto del contrato)')),
                ('obligaciones_adicionales', models.JSONField(blank=True, default=list, help_text='Lista de textos adicionales para la Segunda cláusula.', verbose_name='Obligaciones adicionales del trabajador')),
                ('causales_terminacion_adicionales', models.JSONField(blank=True, default=list, help_text='Lista de literales extra para la Décima cláusula.', verbose_name='Causales de terminación adicionales')),
                ('incluir_politica_celulares', models.BooleanField(default=True, verbose_name='Incluir política de celulares')),
                ('incluir_clausula_invenciones', models.BooleanField(default=True, verbose_name='Incluir cláusula de invenciones')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='registrolabor',
            name='color_cinta',
            field=models.CharField(blank=True, choices=[('MORADA', 'Morada'), ('CAFE', 'Café'), ('NEGRA', 'Negra'), ('NARANJA', 'Naranja'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('BLANCA', 'Blanca'), ('AZUL', 'Azul'), ('HABANO', 'Habano'), ('GRIS', 'Gris')], help_text='Solo para labor Control', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='core.plantillacontrato', verbose_name='Plantilla de contrato'),
        ),
    ]
