# Generated by Django 5.1.4 on 2026-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_plantilla_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='representante_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finca',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
